project_id = "thqxmvjkncyizixbmuwu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.cancel-subscription]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.delete-invitation-code]
verify_jwt = true

[functions.generate-invitation-code]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false